In [1]:
import numpy as np
# create dense matrix
A = np.array([[1,0,0,1,0,0], [0,2,0,0,1,0], [1,0,0,0,0,0], [0,0,1,0,2,0]])
print(A)
# calculate sparsity
sparsity = 1.0 - np.count_nonzero(A) / A.size
print(sparsity)



[[1 0 0 1 0 0]
 [0 2 0 0 1 0]
 [1 0 0 0 0 0]
 [0 0 1 0 2 0]]
0.7083333333333333


Two basic methods for sparse matrix representations are array representation and
linked list representation.

In [2]:
import scipy

In [4]:
import numpy as np
from scipy.sparse import csr_matrix
row = np.array([0, 0, 1, 1, 2, 3])
col = np.array([0, 3, 2, 5, 3, 5]) 
data = np.array([1, 4, 2, 1, 3, 5]) # le 1 est en position 0 0
S = csr_matrix((data, (row, col)),
shape = (4, 6)).toarray()
print(S)

[[1 0 0 4 0 0]
 [0 0 2 0 0 1]
 [0 0 0 3 0 0]
 [0 0 0 0 0 5]]


In [5]:
from numpy import array
from scipy.sparse import csr_matrix
# create dense matrix
A = array([[1,0,0,0,4,0], [0,0,2,0,0,1], [0,0,0,3,0,0],
[0,0,0,0,0,5]])
print("A: \n",A)
# convert to sparse matrix (CSR method)
S = csr_matrix(A)
print("S: \n",S)
# reconstruct dense matrix
B = S.todense()
print("B: \n",B)

A: 
 [[1 0 0 0 4 0]
 [0 0 2 0 0 1]
 [0 0 0 3 0 0]
 [0 0 0 0 0 5]]
S: 
   (0, 0)	1
  (0, 4)	4
  (1, 2)	2
  (1, 5)	1
  (2, 3)	3
  (3, 5)	5
B: 
 [[1 0 0 0 4 0]
 [0 0 2 0 0 1]
 [0 0 0 3 0 0]
 [0 0 0 0 0 5]]
